# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import library_pb2 as proto_dot_library__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in proto/library_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LibraryServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateAuthor = channel.unary_unary(
                '/library.LibraryService/CreateAuthor',
                request_serializer=proto_dot_library__pb2.CreateAuthorRequest.SerializeToString,
                response_deserializer=proto_dot_library__pb2.Author.FromString,
                _registered_method=True)
        self.ListAuthors = channel.unary_unary(
                '/library.LibraryService/ListAuthors',
                request_serializer=proto_dot_library__pb2.ListAuthorsRequest.SerializeToString,
                response_deserializer=proto_dot_library__pb2.ListAuthorsResponse.FromString,
                _registered_method=True)
        self.CreateGenre = channel.unary_unary(
                '/library.LibraryService/CreateGenre',
                request_serializer=proto_dot_library__pb2.CreateGenreRequest.SerializeToString,
                response_deserializer=proto_dot_library__pb2.Genre.FromString,
                _registered_method=True)
        self.ListGenres = channel.unary_unary(
                '/library.LibraryService/ListGenres',
                request_serializer=proto_dot_library__pb2.ListGenresRequest.SerializeToString,
                response_deserializer=proto_dot_library__pb2.ListGenresResponse.FromString,
                _registered_method=True)
        self.CreateBook = channel.unary_unary(
                '/library.LibraryService/CreateBook',
                request_serializer=proto_dot_library__pb2.CreateBookRequest.SerializeToString,
                response_deserializer=proto_dot_library__pb2.Book.FromString,
                _registered_method=True)
        self.ListBooks = channel.unary_unary(
                '/library.LibraryService/ListBooks',
                request_serializer=proto_dot_library__pb2.ListBooksRequest.SerializeToString,
                response_deserializer=proto_dot_library__pb2.ListBooksResponse.FromString,
                _registered_method=True)
        self.UpdateBook = channel.unary_unary(
                '/library.LibraryService/UpdateBook',
                request_serializer=proto_dot_library__pb2.UpdateBookRequest.SerializeToString,
                response_deserializer=proto_dot_library__pb2.Book.FromString,
                _registered_method=True)
        self.AddBookCopy = channel.unary_unary(
                '/library.LibraryService/AddBookCopy',
                request_serializer=proto_dot_library__pb2.AddBookCopyRequest.SerializeToString,
                response_deserializer=proto_dot_library__pb2.BookCopy.FromString,
                _registered_method=True)
        self.ListBookCopies = channel.unary_unary(
                '/library.LibraryService/ListBookCopies',
                request_serializer=proto_dot_library__pb2.ListBookCopiesRequest.SerializeToString,
                response_deserializer=proto_dot_library__pb2.ListBookCopiesResponse.FromString,
                _registered_method=True)
        self.CreateMember = channel.unary_unary(
                '/library.LibraryService/CreateMember',
                request_serializer=proto_dot_library__pb2.CreateMemberRequest.SerializeToString,
                response_deserializer=proto_dot_library__pb2.Member.FromString,
                _registered_method=True)
        self.ListMembers = channel.unary_unary(
                '/library.LibraryService/ListMembers',
                request_serializer=proto_dot_library__pb2.ListMembersRequest.SerializeToString,
                response_deserializer=proto_dot_library__pb2.ListMembersResponse.FromString,
                _registered_method=True)
        self.UpdateMember = channel.unary_unary(
                '/library.LibraryService/UpdateMember',
                request_serializer=proto_dot_library__pb2.UpdateMemberRequest.SerializeToString,
                response_deserializer=proto_dot_library__pb2.Member.FromString,
                _registered_method=True)
        self.BorrowBook = channel.unary_unary(
                '/library.LibraryService/BorrowBook',
                request_serializer=proto_dot_library__pb2.BorrowBookRequest.SerializeToString,
                response_deserializer=proto_dot_library__pb2.Loan.FromString,
                _registered_method=True)
        self.ReturnBook = channel.unary_unary(
                '/library.LibraryService/ReturnBook',
                request_serializer=proto_dot_library__pb2.ReturnBookRequest.SerializeToString,
                response_deserializer=proto_dot_library__pb2.Loan.FromString,
                _registered_method=True)
        self.ListMemberLoans = channel.unary_unary(
                '/library.LibraryService/ListMemberLoans',
                request_serializer=proto_dot_library__pb2.ListMemberLoansRequest.SerializeToString,
                response_deserializer=proto_dot_library__pb2.ListLoansResponse.FromString,
                _registered_method=True)


class LibraryServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateAuthor(self, request, context):
        """Authors
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListAuthors(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateGenre(self, request, context):
        """Genres
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListGenres(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateBook(self, request, context):
        """Books (Metadata)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListBooks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateBook(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddBookCopy(self, request, context):
        """Copies
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListBookCopies(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateMember(self, request, context):
        """Members
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListMembers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateMember(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BorrowBook(self, request, context):
        """Loans
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReturnBook(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListMemberLoans(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LibraryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateAuthor': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateAuthor,
                    request_deserializer=proto_dot_library__pb2.CreateAuthorRequest.FromString,
                    response_serializer=proto_dot_library__pb2.Author.SerializeToString,
            ),
            'ListAuthors': grpc.unary_unary_rpc_method_handler(
                    servicer.ListAuthors,
                    request_deserializer=proto_dot_library__pb2.ListAuthorsRequest.FromString,
                    response_serializer=proto_dot_library__pb2.ListAuthorsResponse.SerializeToString,
            ),
            'CreateGenre': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateGenre,
                    request_deserializer=proto_dot_library__pb2.CreateGenreRequest.FromString,
                    response_serializer=proto_dot_library__pb2.Genre.SerializeToString,
            ),
            'ListGenres': grpc.unary_unary_rpc_method_handler(
                    servicer.ListGenres,
                    request_deserializer=proto_dot_library__pb2.ListGenresRequest.FromString,
                    response_serializer=proto_dot_library__pb2.ListGenresResponse.SerializeToString,
            ),
            'CreateBook': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateBook,
                    request_deserializer=proto_dot_library__pb2.CreateBookRequest.FromString,
                    response_serializer=proto_dot_library__pb2.Book.SerializeToString,
            ),
            'ListBooks': grpc.unary_unary_rpc_method_handler(
                    servicer.ListBooks,
                    request_deserializer=proto_dot_library__pb2.ListBooksRequest.FromString,
                    response_serializer=proto_dot_library__pb2.ListBooksResponse.SerializeToString,
            ),
            'UpdateBook': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateBook,
                    request_deserializer=proto_dot_library__pb2.UpdateBookRequest.FromString,
                    response_serializer=proto_dot_library__pb2.Book.SerializeToString,
            ),
            'AddBookCopy': grpc.unary_unary_rpc_method_handler(
                    servicer.AddBookCopy,
                    request_deserializer=proto_dot_library__pb2.AddBookCopyRequest.FromString,
                    response_serializer=proto_dot_library__pb2.BookCopy.SerializeToString,
            ),
            'ListBookCopies': grpc.unary_unary_rpc_method_handler(
                    servicer.ListBookCopies,
                    request_deserializer=proto_dot_library__pb2.ListBookCopiesRequest.FromString,
                    response_serializer=proto_dot_library__pb2.ListBookCopiesResponse.SerializeToString,
            ),
            'CreateMember': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateMember,
                    request_deserializer=proto_dot_library__pb2.CreateMemberRequest.FromString,
                    response_serializer=proto_dot_library__pb2.Member.SerializeToString,
            ),
            'ListMembers': grpc.unary_unary_rpc_method_handler(
                    servicer.ListMembers,
                    request_deserializer=proto_dot_library__pb2.ListMembersRequest.FromString,
                    response_serializer=proto_dot_library__pb2.ListMembersResponse.SerializeToString,
            ),
            'UpdateMember': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateMember,
                    request_deserializer=proto_dot_library__pb2.UpdateMemberRequest.FromString,
                    response_serializer=proto_dot_library__pb2.Member.SerializeToString,
            ),
            'BorrowBook': grpc.unary_unary_rpc_method_handler(
                    servicer.BorrowBook,
                    request_deserializer=proto_dot_library__pb2.BorrowBookRequest.FromString,
                    response_serializer=proto_dot_library__pb2.Loan.SerializeToString,
            ),
            'ReturnBook': grpc.unary_unary_rpc_method_handler(
                    servicer.ReturnBook,
                    request_deserializer=proto_dot_library__pb2.ReturnBookRequest.FromString,
                    response_serializer=proto_dot_library__pb2.Loan.SerializeToString,
            ),
            'ListMemberLoans': grpc.unary_unary_rpc_method_handler(
                    servicer.ListMemberLoans,
                    request_deserializer=proto_dot_library__pb2.ListMemberLoansRequest.FromString,
                    response_serializer=proto_dot_library__pb2.ListLoansResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'library.LibraryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('library.LibraryService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LibraryService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateAuthor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/library.LibraryService/CreateAuthor',
            proto_dot_library__pb2.CreateAuthorRequest.SerializeToString,
            proto_dot_library__pb2.Author.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListAuthors(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/library.LibraryService/ListAuthors',
            proto_dot_library__pb2.ListAuthorsRequest.SerializeToString,
            proto_dot_library__pb2.ListAuthorsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateGenre(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/library.LibraryService/CreateGenre',
            proto_dot_library__pb2.CreateGenreRequest.SerializeToString,
            proto_dot_library__pb2.Genre.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListGenres(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/library.LibraryService/ListGenres',
            proto_dot_library__pb2.ListGenresRequest.SerializeToString,
            proto_dot_library__pb2.ListGenresResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateBook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/library.LibraryService/CreateBook',
            proto_dot_library__pb2.CreateBookRequest.SerializeToString,
            proto_dot_library__pb2.Book.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListBooks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/library.LibraryService/ListBooks',
            proto_dot_library__pb2.ListBooksRequest.SerializeToString,
            proto_dot_library__pb2.ListBooksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateBook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/library.LibraryService/UpdateBook',
            proto_dot_library__pb2.UpdateBookRequest.SerializeToString,
            proto_dot_library__pb2.Book.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddBookCopy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/library.LibraryService/AddBookCopy',
            proto_dot_library__pb2.AddBookCopyRequest.SerializeToString,
            proto_dot_library__pb2.BookCopy.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListBookCopies(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/library.LibraryService/ListBookCopies',
            proto_dot_library__pb2.ListBookCopiesRequest.SerializeToString,
            proto_dot_library__pb2.ListBookCopiesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateMember(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/library.LibraryService/CreateMember',
            proto_dot_library__pb2.CreateMemberRequest.SerializeToString,
            proto_dot_library__pb2.Member.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListMembers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/library.LibraryService/ListMembers',
            proto_dot_library__pb2.ListMembersRequest.SerializeToString,
            proto_dot_library__pb2.ListMembersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateMember(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/library.LibraryService/UpdateMember',
            proto_dot_library__pb2.UpdateMemberRequest.SerializeToString,
            proto_dot_library__pb2.Member.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BorrowBook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/library.LibraryService/BorrowBook',
            proto_dot_library__pb2.BorrowBookRequest.SerializeToString,
            proto_dot_library__pb2.Loan.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReturnBook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/library.LibraryService/ReturnBook',
            proto_dot_library__pb2.ReturnBookRequest.SerializeToString,
            proto_dot_library__pb2.Loan.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListMemberLoans(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/library.LibraryService/ListMemberLoans',
            proto_dot_library__pb2.ListMemberLoansRequest.SerializeToString,
            proto_dot_library__pb2.ListLoansResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
